# Generated by Django 6.0.1 on 2026-01-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
