# Generated by Django 6.0.1 on 2026-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
